### ISSUE TITLE
Missing indexPath entries in switch leads to crash

### ISSUE THREAD

**Issue by jlindenbaum** [matghazaryan/AMSlideMenu2#21]
I was playing around with release 1.5.2, and followed the video to hook things up. I created three static cells, but in my `segueIdentifierForIndexPathInLeftMenu` I only had `case 2` returning a string, the others just left the identifier `nil`.

This leads to a crash in my MainViewController with a message telling me I do not have a leftMenu segue.

`
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Receiver (<MainViewController: 0x8c95e80>) has no segue with identifier 'rightMenu''
`

Took me a while to figure out that only if I implement all cases in `segueIdentifierForIndexPathInLeftMenu` does it work.

I realize this is a bit of an edge case, but it would be nice to handle this a bit more gracefully than a full-on crash of the app.

**Comment by Teng1990** [comment]
I've changed, - (NSIndexPath *)initialIndexPathForLeftMenu
{
    return [NSIndexPath indexPathForRow:2 inSection:0];
}
but still won't do, why is this
