### ISSUE TITLE
Disabling Pan Gesture Recognizer

### ISSUE THREAD

**Issue by Phloxx1** [matghazaryan/AMSlideMenu2#24]
In your documentation you have code to disable the Pan gesture for right, and left.
but it seems to only work outside of story board. I am using story board for my application, so unfortunately the code did not work.
Do you have a code to disable even with the use of storyboard?

**Comment by tamedras** [comment]
Hi,

You can comment out the contents of the function "viewWillDisappear" on UIViewController+AMSlideMen.m . This worked for me !

- (void)my_viewWillDisappear:(BOOL)animated
{
    // Additional code Here
    
    // Enabling pan gesture for left and right menus
 //   AMSlideMenuMainViewController *mainVC = [AMSlideMenuMainViewController getInstanceForVC:self];
 //   mainVC.leftPanDisabled = NO;
 //   mainVC.rightPanDisabled = NO;

    // Call original viewWillDisappear method
    [self my_viewWillDisappear:animated];
}
