### ISSUE TITLE
AMSlideMenu with TabBarController

### ISSUE THREAD

**Issue by aUbilla** [matghazaryan/AMSlideMenu2#44]
Hello, first of all, thank you for this script, it's really great! 

But I have tried to modify (in the demo), and instead of putting a navigationController I changed for tabBarController and click the firstRow or secondRow the application goes down, you can not use a tabBarController?

**Comment by daljeet16** [comment]
Hi All 

I'm also implementing AMSlideMenu using tab bar controller.I want to know that above storyboard structure is working fine in your case , so i cant implement in the same way. 

Thanks!
