### ISSUE TITLE
status bar animation

### ISSUE THREAD

**Issue by motokotomax** [matghazaryan/AMSlideMenu2#64]
Hello, I want to add animation like on your gif (status bar background) https://camo.githubusercontent.com/2f52a3eb68e90024ec5507e7f49b89217a4bd45c/68747470733a2f2f7261772e6769746875622e636f6d2f61727475726465762f414d536c6964654d656e752f6d61737465722f414d536c6964654d656e7544656d6f2d7769746825323053746f7279626f6172642f414d536c6964654d656e752f64656d6f2e676966 Whаt I have to do for this?

Thank you for your control!

**Comment by Hema492** [comment]
Hi, but the app is not same as shown in GIF. :(
