### ISSUE TITLE
Has no segue with identifier 'rightMenu''

### ISSUE THREAD

**Issue by AsawariNagarkar** [matghazaryan/AMSlideMenu2#68]
My application is still crashing.

'Receiver (<MainVC: 0x8d57910>) has no segue with identifier 'rightMenu''

Please elaborate about corrections to be done

**Comment by khaledannajar** [comment]
I had the same problem and I was using the AMSlideMenu using storyboard. 
The fix was just that I did not return the right segue identifier in this method
-(NSString *) segueIdentifierForIndexPathInLeftMenu:(NSIndexPath *)indexPath

I was only returning @"", so I returned the segue identifiers I named in the storyboard.

**Comment by MarioBajr** [comment]
post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', 'AMSlideMenuWithoutStoryboards']
    end
  end
end

**Comment by douglasddf** [comment]
The tip from MarioBarj works for me. :) Thanks!

**Comment by rjcristy** [comment]
I solved mine by copying the prefix files from the library to my app's prefix file. Thanks AMSlideMenu such a great app.

**Comment by Duffycola** [comment]
Wow, sorry to say this, but it is really annoying.

I followed the instructions, got this exception when the main ViewController would load (not even performing the segue manually)...

I got to the point where I:

- added the prefix header manually
- defined the segue names in segueIdentifierForIndexPathInLeftMenu and segueIdentifierForIndexPathInRightMenu
- set GCC_PREPROCESSOR_DEFINITIONS to '$(inherited) AMSlideMenuWithoutStoryboards' (I wasn't using cocoa pods)

and still had a problem with  `SYSTEM_VERSION_LESS_THAN(@"7.0")` undefined

I then realised the prefix header just wouldn't be respected, so I changed all occurrences of `SYSTEM_VERSION_LESS_THAN(@"7.0")`
to
`[[[UIDevice currentDevice] systemVersion] floatValue] < 7.0`

Apparently using the prefix header is discouraged => Any define that is really necessary (try not to use them) should be placed into your own headers.

Now the view does load, but when I click no the segue, the problem still remains that I now get the error for the left segue...

'Receiver (<SlideMenuViewController: 0x7fa9237cbb70>) has no segue with identifier 'leftMenu''

where SlideMenuViewController inherits from AMSlideMenuLeftTableViewController

**Comment by AndyIbanez** [comment]
Unfortunately I'm having the same problem, also with Swift. I can't use Mario's solution because I don't want to use Storyboards.

I have no clue why it's crashing. This is my call stack:

```TEXT
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f30e7c5 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000111311dcd objc_exception_throw + 48
	2   UIKit                               0x0000000110102ec0 -[UIViewController shouldPerformSegueWithIdentifier:sender:] + 0
	3   MALvado                             0x000000010f1122d9 -[AMSlideMenuMainViewController setup] + 1065
	4   MALvado                             0x000000010f10f526 -[AMSlideMenuMainViewController viewDidLoad] + 390
	5   UIKit                               0x0000000110100198 -[UIViewController loadViewIfRequired] + 860
	6   UIKit                               0x00000001101004e7 -[UIViewController view] + 27
	7   UIKit                               0x000000010ffe2b6c -[UIWindow addRootViewControllerViewIfPossible] + 61
	8   UIKit                               0x000000010ffe3269 -[UIWindow _setHidden:forced:] + 302
	9   UIKit                               0x000000010fff4a04 -[UIWindow makeKeyAndVisible] + 43
	10  UIKit                               0x000000010ff76b16 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3975
	11  UIKit                               0x000000010ff7ca6a -[UIApplication _runWithMainScene:transitionContext:completion:] + 1755
	12  UIKit                               0x000000010ff7a208 -[UIApplication workspaceDidEndTransaction:] + 188
	13  FrontBoardServices                  0x0000000115724c0f -[FBSSerialQueue _performNext] + 192
	14  FrontBoardServices                  0x0000000115724f7d -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	15  CoreFoundation                      0x000000010f238ba1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x000000010f22eacc __CFRunLoopDoSources0 + 556
	17  CoreFoundation                      0x000000010f22df83 __CFRunLoopRun + 867
	18  CoreFoundation                      0x000000010f22d998 CFRunLoopRunSpecific + 488
	19  UIKit                               0x000000010ff79ba5 -[UIApplication _run] + 402
	20  UIKit                               0x000000010ff7e2cb UIApplicationMain + 171
	21  MALvado                             0x000000010f10d67d main + 109
	22  libdyld.dylib                       0x0000000111cf892d start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by starikovvm** [comment]
I have encountered the same issue. The reason of it was that I added "use_frameworks!" to my Podfile, Removing this line solved the problem.

**Comment by haroldogtf** [comment]
Works for me as MarioBajr and douglasddf said

I just have to change project for pods_project

    post_install do |installer_representation|
       installer_representation.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', 'AMSlideMenuWithoutStoryboards']
        end
      end
    end

**Comment by harshag** [comment]
Facing same issue. Changed pods file to include code as suggested by @haroldogtf but getting below error
`/projectpath/Pods/AMSlideMenu/AMSlideMenu/AMSlideMenuMainViewController.m:459:17: Implicit declaration of function 'SYSTEM_VERSION_LESS_THAN' is invalid in C99`

**Comment by mrgerych** [comment]
```
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AMSlideMenuWithoutStoryboards']
    end
  end
#fix for AMSlideMenu
  define = '#define SYSTEM_VERSION_LESS_THAN(v) ' +
            '([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedAscending)'

  directory = installer_representation.config.project_pods_root + 'Target Support Files/'
  info_plist_path = directory + "AMSlideMenu/AMSlideMenu-prefix.pch"

  text = File.read(info_plist_path)
  new_contents = text+define
  File.open(info_plist_path, "w") {|file| file.puts new_contents }

end
```

**Comment by jt3k** [comment]
i install cocoapods  
after this  i change directory to project root and  run  pod init in terminal

after this  i copy and paste [this full fix](https://github.com/SocialObjects-Software/AMSlideMenu/issues/68#issuecomment-206320590) to podfile

after this i run `pod install`

now there is error in terminal
![](https://i.imgur.com/ZKdIPmn.png)

HOW TO FIX THIS ISSUE? ?
MAY BE REOPEN??

**Comment by AndyIbanez** [comment]
I don’t think your issue is related to this one at all.

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.1.25&pv=10.12.1&source=email_footer_2]
On Fri, Nov 11, 2016 at 8:44 AM, Andrey Gurtovoy <notifications@github.com> wrote:
i install cocoapods

after this i change directory to project root and run pod init in terminal

after this i copy and paste this full fix [https://github.com/SocialObjects-Software/AMSlideMenu/issues/68#issuecomment-206320590] to podfile

after this i run pod install

now there is error in terminal
[https://camo.githubusercontent.com/0130b2958198acc69fd6c78672e028eccdb62ea3/68747470733a2f2f692e696d6775722e636f6d2f5a4b6449506d6e2e706e67]

HOW TO FIX THIS ISSUE? ?
MAY BE REOPEN??
