### ISSUE TITLE
Content view not shown up

### ISSUE THREAD

**Issue by sanitlee** [matghazaryan/AMSlideMenu2#89]
Hi Arthur - I've been trying to implement your lib w/o storyboard for my existing proj. I've followed your instruction on Youtube https://www.youtube.com/watch?v=BgcRc7D3qJw but can't get it work yet. As I just want to have left slide-out menu, I have excluded all right one related. What I see is only left menu in full screen without content view showing up. My content view is just UIView Controller with UINavigation Controller. My delegate has IF to check user login. If user already login then it'll go right into my first content view controller via my main view controller created following your instruction. If not, it'll go into welcome view controller. Btw, I'm using Parse as my backend, so there's some Parse config in my delegate as well. So my questions are:
- What do you think where else I have to look into?
- Do I need to modify anything in your lib?

Not sure my info given enough for you to analyse my problem. If not, please let me know.
Appreciate your works! Thanks :-)
Sanit

**Comment by DavidMorenoDWeb** [comment]
Did you fix it? I'm having the same problem =(

**Comment by sanitlee** [comment]
@DavidMorenoDWeb I just opted for another way as for this one I can't figure out.

**Comment by DavidMorenoDWeb** [comment]
Ok, thank you!
